# docker-compose.yml
services:
  sentry:
    build: .
    image: sentry
    container_name: sentry
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json 
    secrets:
      - discord_token
      - postgres_password
    networks:
      - dbnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dbnet:
    external: true 

secrets:
  discord_token:
    file: ./secrets/discord_token.txt
  postgres_password:
    file: ./secrets/postgres_password.txt